modName = CrankShaft
modId = flywheel
modGroup = dev.engine_room
modArchivesBaseName = crankshaft

vanillinId = vanillin
vanillinName = Vanillate

minecraftVersion = 1.12.2
developmentEnvironmentUserName = Developer

accessTransformersFile = META-INF/flywheel_at.cfg

usesMixins = true
mixinConfigRefmap = mixins.flywheel.refmap.json

coreModClass = flywheel.backend.core.FlwCorePlugin

customMavenPublishUrl = https://repo.warfactory.co/releases
mavenArtifactGroup = dev.engine_room

generateGradleTokenClass = dev.engine_room.flywheel.Tags
gradleTokenModId = MODID
gradleTokenModName = MODNAME
gradleTokenVersion = VERSION

additionalJavaArguments = -Xmx4G;-XX:+UseG1GC
