org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=26.2
neo_version=26.2.0.59
fabric_loader_version=0.19.3
fabric_api_version=0.157.0+26.2
sodium_version=0.9.1+mc26.2
mod_id=flywheel
mod_name=CrankShaft
mod_version=1.0.0
mod_group_id=dev.engine_room
vanillin_id=vanillin
vanillin_name=Vanillate
