// SPDX-License-Identifier: LGPL-3.0-only
// Copyright (C) 2023-2026 Cortex and Nvidium contributors
// Copyright (C) 2026 movblock

layout(local_size_x = 64) in;

layout(std430, binding = 0) restrict readonly buffer Src {
    uint src[];
};
layout(std430, binding = 1) restrict writeonly buffer Dst {
    uint dst[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= dst.length()) {
        return;
    }
    dst[i] = src[i];
}
