#version 430 compatibility
layout(local_size_x = 8, local_size_y = 8) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);
uniform vec2 screenSize;
uniform sampler2D colortex0;
uniform sampler2D colortex1;
uniform sampler2D colortex2;
uniform sampler2D depthtex1;
_FLW_ITERATION_LAYERS
_FLW_ITERATION_MATERIALS
void main() {
    if (!flw_oitActive || (flw_pad & 0x00ffffffu) <= 1u) return;
    uvec2 p = gl_GlobalInvocationID.xy;
    if (any(greaterThanEqual(p, uvec2(screenSize)))) return;
    uint pixel = p.y * uint(screenSize.x) + p.x;
    if(pixel==0u) atomicOr(flw_pad,0x40000000u);
    vec4 albedo = texelFetch(colortex0, ivec2(p), 0);
    vec4 data = texelFetch(colortex1, ivec2(p), 0);
    vec4 normal = texelFetch(colortex2, ivec2(p), 0);
    flw_opaque[pixel * 2u] = uvec4(packHalf2x16(albedo.rg), packHalf2x16(albedo.ba),
                                  packUnorm2x16(data.xy), packUnorm2x16(data.zw));
    flw_opaque[pixel * 2u + 1u] = uvec4(packUnorm2x16(normal.xy), packUnorm2x16(normal.zw),
                                      floatBitsToUint(texelFetch(depthtex1, ivec2(p), 0).r), 0u);
}
